language: python
sudo: required
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "nightly"
before_install:
    - sudo apt-get update -qq
    # Use standard ubuntu packages in their default version
    - sudo apt-get install -qq python-scipy
script: "make test"
