language: python
virtualenv:
  system_site_packages: true
sudo: required
before_install:
  - openssl aes-256-cbc -K $encrypted_6d2b7347f8c6_key -iv $encrypted_6d2b7347f8c6_iv
    -in variables.enc -out variables -d
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-dev python-scipy
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - git checkout 2.4.11
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_DOCS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_opencv_java=OFF
    -DBUILD_JASPER=ON -DWITH_JASPER=ON -DBUILD_ZLIB=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF
    -DBUILD_PERF_TESTS=OFF -DWITH_OPENEXR=OFF -DBUILD_PNG=ON -DWITH_PNG=ON -DWITH_TIFF=ON
    -DBUILD_TIFF=ON -DWITH_WEBP=OFF -DWITH_JPEG=ON -DBUILD_JPEG=ON ..
  - make -j4
  - sudo make -j4 install
  - cd ../..
install:
  - pip install py2neo
  - source variables
before_script:
  - mysql -uroot -e "create database test_db;"
  - mysql -uroot test_db < scripts/testdata.sql
script: make test
notifications:
  slack:
    secure: V9CFftjWKzpbi6F1v24/t43k5ajsNaa/b7kQGjDabH18EYSm5fP07RFBModWtACNgWEL1q1ZBo+pPQQiczMoDI2W/Iac7PUYjzUbiU+lirxeDAukP/WN5yl5nBHqNdQhSeEoacq0RjTdyx0BOaTO/bovpqeao7OlCzo90WtiDX6T18tFsOxs7tGtTHS7u52KHCAEcykB5JaA1B9ZxjksMD7fvkZRMhHud3vK0Ybnh3VqyKVSqCCDZhiHdnUPVl2uXrOyGisVMYKKnDLVBuBA20esQTbDaO9KhlUc4b909GZ2SIeETuVfPWvY6Oj4BwJRZs3MJlUzHpjK8YHCp/tcf17yX0NQVjXNiZ/HHVVbwWO2CboM+5QnwudetNp6Q/5dHg5GFpaGchjHN0hE2eN5G7Y0AoSeIUsD7+52RW8AmhYnoWhTDpcNGfCzafTkLxCcjYi693UDRPR/HZ3TZPI2hAx0s4kv1eau0m8wA2wKELDRHL+rt7j8D1s+GF+JchPIfOJjy0bAdEgasMKVombmA81m/UxAmMCnxBbyx7rsZYYfq0W2UuC5tYnYs1i2LjYwN052fz9E3edw0NtBvrSgrKB/PuD1ZrEQKRHsa/fW0Zh0ofDe6ra3VcmpK81T1loi5BuPILWMQ1lSiQLqihkVkEggiLHVZCgm5JxdB3eDUOg=
